In [20]:
from sklearn.preprocessing import LabelBinarizer
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.datasets import mnist
from tensorflow.keras import backend as K
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt
import numpy as np

In [21]:
(x_train , y_train),(x_test,y_test) = mnist.load_data()

In [22]:
x_train.shape

(60000, 28, 28)

In [23]:
y_train.shape

(60000,)

In [24]:
x_train = x_train.reshape(x_train.shape[0],28*28*1)
x_test = x_test.reshape(x_test.shape[0],28*28*1)

In [25]:
x_train.shape

(60000, 784)

In [26]:
x_train = x_train.astype("float32") / 255.0

x_train[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [27]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [28]:
lb = LabelBinarizer()
y_train = lb.fit_transform(y_train)
y_test = lb.transform(y_test)

y_train

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0]])

In [29]:
y_train.shape

(60000, 10)

In [32]:
import tensorflow as tf

class MyModel(tf.keras.Model):

  def __init__(self):
    super().__init__()
    self.dense1 = Dense(256, input_shape=(784,), activation="relu")
    self.dense2 = Dense(128, input_shape=(256,), activation="relu")
    self.dense3 = Dense(10, input_shape=(128,), activation="softmax")

  def call(self, inputs, training=False):
    x = self.dense1(inputs)
    x = self.dense2(x)
    x = self.dense3(x)
    return x


model = MyModel()

In [33]:
sgd = SGD(learning_rate=0.05)

model.compile(loss="categorical_crossentropy", optimizer=sgd, metrics=["accuracy"])
trained_model = model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=100, batch_size=100)

Epoch 1/100
600/600 [==============================] - 4s 6ms/step - loss: 0.5018 - accuracy: 0.8658 - val_loss: 34.4895 - val_accuracy: 0.9234
Epoch 2/100
600/600 [==============================] - 3s 6ms/step - loss: 0.2393 - accuracy: 0.9313 - val_loss: 26.4780 - val_accuracy: 0.9393
Epoch 3/100
600/600 [==============================] - 3s 6ms/step - loss: 0.1861 - accuracy: 0.9462 - val_loss: 21.5140 - val_accuracy: 0.9504
Epoch 4/100
600/600 [==============================] - 3s 6ms/step - loss: 0.1525 - accuracy: 0.9558 - val_loss: 20.7875 - val_accuracy: 0.9526
Epoch 5/100
600/600 [==============================] - 4s 6ms/step - loss: 0.1275 - accuracy: 0.9631 - val_loss: 18.8374 - val_accuracy: 0.9552
Epoch 6/100
600/600 [==============================] - 3s 6ms/step - loss: 0.1104 - accuracy: 0.9682 - val_loss: 16.0080 - val_accuracy: 0.9638
Epoch 7/100
600/600 [==============================] - 4s 6ms/step - loss: 0.0962 - accuracy: 0.9718 - val_loss: 15.8567 - val_accuracy:

In [35]:
model.evaluate(x_test,y_test)

model.summary()

313/313 [==============================] - 2s 4ms/step - loss: 22.2173 - accuracy: 0.9783
Model: "my_model_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               multiple                  200960    
                                                                 
 dense_1 (Dense)             multiple                  32896     
                                                                 
 dense_2 (Dense)             multiple                  1290      
                                                                 
Total params: 235,146
Trainable params: 235,146
Non-trainable params: 0
_________________________________________________________________
