# 19BCE123: JASH MAVANI

## Practical 6

Build a language model using RNN. Write functionsto sample novel sentences and find the probability ofinput sentence. Also, use Recurrent Neural Network for Sentiment Analysis

In [1]:
from tensorflow import keras
import numpy
from numpy import array
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import SimpleRNN
from keras.layers import Embedding
from keras.preprocessing.sequence import pad_sequences

data = """ Jack and Jill went up the hill .\n To fetch a pail of water .\n Jack fell down and broke his crown .\n And Jill came tumbling after ."""
# print("Data:", data, type(data))

data_splitted=data.split('\n') #returns a list of strings
print("Data_Splitted:", data_splitted, type(data_splitted))

Data_Splitted: [' Jack and Jill went up the hill .', ' To fetch a pail of water .', ' Jack fell down and broke his crown .', ' And Jill came tumbling after .'] <class 'list'>


In [2]:
tokenizer=Tokenizer(filters='!"#$%&()*+,-/:;<=>?@[\]^_`{|}~')

tokenizer.fit_on_texts(data_splitted) #learns a vocabulary
print("Word Indices:", tokenizer.word_index) #tokenizer.word_index is a dictionary

vocab_size = len(tokenizer.word_index) + 1
print("Vocab Size:", vocab_size)

sequences=tokenizer.texts_to_sequences(data_splitted) #list of list
l=len(sequences)
print("Sequences:",sequences, type(sequences), l)


Word Indices: {'.': 1, 'and': 2, 'jack': 3, 'jill': 4, 'went': 5, 'up': 6, 'the': 7, 'hill': 8, 'to': 9, 'fetch': 10, 'a': 11, 'pail': 12, 'of': 13, 'water': 14, 'fell': 15, 'down': 16, 'broke': 17, 'his': 18, 'crown': 19, 'came': 20, 'tumbling': 21, 'after': 22}
Vocab Size: 23
Sequences: [[3, 2, 4, 5, 6, 7, 8, 1], [9, 10, 11, 12, 13, 14, 1], [3, 15, 16, 2, 17, 18, 19, 1], [2, 4, 20, 21, 22, 1]] <class 'list'> 4


In [3]:
X=list()
y=list()

for i in range(len(sequences)):
  X.insert(i,sequences[i][:-1])
  y.insert(i,sequences[i])

print("X=", X, "y=",y, type(X), type(y))

X= [[3, 2, 4, 5, 6, 7, 8], [9, 10, 11, 12, 13, 14], [3, 15, 16, 2, 17, 18, 19], [2, 4, 20, 21, 22]] y= [[3, 2, 4, 5, 6, 7, 8, 1], [9, 10, 11, 12, 13, 14, 1], [3, 15, 16, 2, 17, 18, 19, 1], [2, 4, 20, 21, 22, 1]] <class 'list'> <class 'list'>


In [4]:
maxlen = max([len(sequence) for sequence in X])
print("Maxlen:",maxlen)

#X=array(X)
#y=array(y)
#X=numpy.reshape(X,newshape=(l,-1))
#y=numpy.reshape(y,newshape=(l,-1))

X=pad_sequences(X,maxlen=maxlen+1,padding='pre') # +1 to have 0 as the first input
print("X:",X, type(X), X.shape)
y=pad_sequences(y,maxlen=maxlen+1,padding='pre')
print("y:",y, type(y), y.shape)

#z=numpy.
#for i in range(l):
#  z[i]=to_categorical(y[i],num_classes=vocab_size)  

#print("X=", X, "y=",y)
y=to_categorical(y,num_classes=vocab_size)

print("X=", X, "y=",y, type(X), type(y), X.shape, y.shape)
model=Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=10))
print(model.output_shape)
model.add(SimpleRNN(units=50, return_sequences=True))
print(model.output_shape)
model.add(Dense(units=vocab_size,activation='softmax'))
model.summary()
print("Input Shape of all Layers:",model.layers[0].input_shape,model.layers[1].input_shape,model.layers[2].input_shape)
print("Input Dim:",model.layers[0].input_dim)


Maxlen: 7
X: [[ 0  3  2  4  5  6  7  8]
 [ 0  0  9 10 11 12 13 14]
 [ 0  3 15 16  2 17 18 19]
 [ 0  0  0  2  4 20 21 22]] <class 'numpy.ndarray'> (4, 8)
y: [[ 3  2  4  5  6  7  8  1]
 [ 0  9 10 11 12 13 14  1]
 [ 3 15 16  2 17 18 19  1]
 [ 0  0  2  4 20 21 22  1]] <class 'numpy.ndarray'> (4, 8)
X= [[ 0  3  2  4  5  6  7  8]
 [ 0  0  9 10 11 12 13 14]
 [ 0  3 15 16  2 17 18 19]
 [ 0  0  0  2  4 20 21 22]] y= [[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[

2022-05-04 17:02:07.378724: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [5]:
model.compile(optimizer="rmsprop", loss="categorical_crossentropy", metrics=['accuracy'])

model.fit(X, y, epochs=200, verbose=0)

2022-05-04 17:02:07.697142: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


In [6]:
def sample_seq_wo_seed(model, tokenizer, n_words, vocab_size): #only the first word is sampled
  encoded=list()
  in_text = ''
    # generate a fixed number of words = n_words
  for i in range(n_words):
  # encode the text as integer
    encoded = tokenizer.texts_to_sequences([in_text])[0] # for words not in the vocab it returns []
        # pre-pad sequences to a fixed length
    #encoded = pad_sequences([encoded], maxlen=max_length, padding='pre')
    encoded.insert(0,0)
    encoded=array(encoded)
    encoded=numpy.reshape(encoded,newshape=(1,-1))
    print("i:", i, "Encoded:",encoded, encoded.shape)
        # predict probability and sample a word from vocab
    if i == 0:
      prob = model.predict(encoded, verbose=0)
      print("i=", i, "Prob:", prob, type(prob), prob.shape)
      yhat=0
      while yhat == 0:
        yhat=numpy.random.choice(range(vocab_size),p=prob.ravel())
        yhat=[yhat]
        yhat=array(yhat)
        yhat=numpy.reshape(yhat,newshape=(1,-1))
        print("i:",i,"If yhat:", yhat, yhat.shape)
    else:
      yhat=numpy.append(yhat,0)
      yhat=numpy.reshape(yhat,newshape=(1,-1))
      while yhat[0,i] == 0:
        yhat=model.predict_classes(encoded, verbose=0)
        print("i:", i, "Else yhat:", yhat, yhat.shape)

      # map predicted word index to word
    out_word = ''
    for word, index in tokenizer.word_index.items():
      if index == yhat[0,i]:
        out_word = word
      #print("index:", index, "out_word:", out_word)
      break

    # append to input
    in_text = in_text + out_word + ' '
    return in_text

print(tokenizer.word_index.items())

print("------------------Sample Sequence without Seed---------------------------------")
print(sample_seq_wo_seed(model, tokenizer, 8, vocab_size))
print("-------------------------------------------------------------------------------")



dict_items([('.', 1), ('and', 2), ('jack', 3), ('jill', 4), ('went', 5), ('up', 6), ('the', 7), ('hill', 8), ('to', 9), ('fetch', 10), ('a', 11), ('pail', 12), ('of', 13), ('water', 14), ('fell', 15), ('down', 16), ('broke', 17), ('his', 18), ('crown', 19), ('came', 20), ('tumbling', 21), ('after', 22)])
------------------Sample Sequence without Seed---------------------------------
i: 0 Encoded: [[0]] (1, 1)
i= 0 Prob: [[[4.5235544e-01 4.9005174e-03 2.2245243e-03 4.7277296e-01 2.6143335e-03
   3.3424522e-03 3.7387398e-04 5.4922199e-04 9.8000583e-04 2.8255126e-02
   1.4836866e-03 3.4375762e-04 1.7216681e-04 2.3620427e-03 1.0189934e-02
   2.5542597e-03 8.5652294e-04 1.9122451e-03 1.8990139e-03 5.8988533e-03
   7.3190709e-04 7.6861482e-04 2.4585449e-03]]] <class 'numpy.ndarray'> (1, 1, 23)
i: 0 If yhat: [[3]] (1, 1)
 
-------------------------------------------------------------------------------


In [7]:

def prob_of_input_sentence(model, tokenizer, sentence):
  print("Input Sentence:", sentence)
  encoded=tokenizer.texts_to_sequences([sentence])[0]
  encoded.insert(0,0)
  encoded=array(encoded)
  encoded=numpy.reshape(encoded,newshape=(1,-1))
  print("Encoded:", encoded, encoded.shape)
  prob=model.predict(encoded, verbose=0)
  print("Prob:", prob, prob.shape)
  probability=1
  for i in range(prob.shape[1]-1):
    probability = probability * prob[0,i,encoded[0,i+1]]
  print("Probability of Sentence", "\"", sentence, "\"", "is:", probability)

In [8]:
print("-------------------Probability of Input Sentence------------------------------")  
prob_of_input_sentence(model, tokenizer, "Jack and Jill Went")
prob_of_input_sentence(model, tokenizer, "and Jill Went up")
prob_of_input_sentence(model, tokenizer, "went up the hill")
prob_of_input_sentence(model, tokenizer, "jack and Jill Went up the hill .")
prob_of_input_sentence(model, tokenizer, "to fetch a pail")
prob_of_input_sentence(model, tokenizer, "fetch a pail")
prob_of_input_sentence(model, tokenizer, "to fetch a pail of water")
prob_of_input_sentence(model, tokenizer, "jack fell down and")
prob_of_input_sentence(model, tokenizer, "jack fell down and broke")
prob_of_input_sentence(model, tokenizer, "fell down and broke")
prob_of_input_sentence(model, tokenizer, "jack fell down and broke his crown")
prob_of_input_sentence(model, tokenizer, "and jill came tumbling")
prob_of_input_sentence(model, tokenizer, "jill came tumbling after")
prob_of_input_sentence(model, tokenizer, "and jill came tumbling after .")
print("-------------------------------------------------------------------------------")


-------------------Probability of Input Sentence------------------------------
Input Sentence: Jack and Jill Went
Encoded: [[0 3 2 4 5]] (1, 5)
Prob: [[[4.52355444e-01 4.90051741e-03 2.22452427e-03 4.72772956e-01
   2.61433353e-03 3.34245223e-03 3.73873976e-04 5.49221993e-04
   9.80005832e-04 2.82551255e-02 1.48368662e-03 3.43757623e-04
   1.72166809e-04 2.36204267e-03 1.01899337e-02 2.55425973e-03
   8.56522936e-04 1.91224506e-03 1.89901388e-03 5.89885330e-03
   7.31907086e-04 7.68614816e-04 2.45854491e-03]
  [2.94998623e-02 5.51393861e-03 4.49529499e-01 5.49026590e-04
   1.48039113e-03 2.01932271e-03 9.90383443e-04 1.13331160e-04
   4.71957646e-05 6.53730258e-02 1.41628906e-02 5.26781334e-03
   8.92461103e-05 4.63463221e-06 5.90484124e-04 4.20562088e-01
   1.67621882e-03 1.05325824e-04 5.45545830e-04 6.71191840e-04
   8.01530376e-04 1.20026780e-04 2.87024537e-04]
  [8.37955740e-04 3.36204976e-04 7.74183916e-03 2.69011827e-04
   7.74801016e-01 9.96433664e-04 2.88725947e-04 2.81397108e